name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: 发行版本
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
      - name: 检出代码
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}      
      - name: 安装依赖
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE }}
        if: ${{ steps.release.outputs.release_created }}
      - name: 构建
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      - name: 发布到 nom
        run: npm run pub
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: 同步 cnpm
        run: npm run sync
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}